SRCROOT = ../../..

include $(SRCROOT)/Makefile.include

OBJS = AsciiOutputStream.o DrftpdFileFilter.o FileExistsException.o FtpRequest.o InvalidDirectoryException.o PermissionDeniedException.o SFVFile.o TransferStatus.o

all: $(OBJS)
