/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_mog_io_FileSystem */

#ifndef _Included_se_mog_io_FileSystem
#define _Included_se_mog_io_FileSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_mog_io_FileSystem
 * Method:    getFileSystem
 * Signature: ()Lse/mog/io/FileSystem;
 */
JNIEXPORT jobject JNICALL Java_se_mog_io_FileSystem_getFileSystem
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
