package net.sf.drftpd.master.usermanager;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import net.sf.drftpd.DuplicateElementException;

import org.apache.oro.text.GlobCompiler;
import org.apache.oro.text.regex.MalformedPatternException;
import org.apache.oro.text.regex.Pattern;
import org.apache.oro.text.regex.Perl5Matcher;

/**
 * Generic user class. 
 *
 * @author <a href="mailto:rana_b@yahoo.com">Rana Bhattacharyya</a>
 */

public abstract class AbstractUser extends User {

	protected String username;
	protected String comment;
	protected String tagline;
	
	//collections - initalized when usermanager load():s
	protected ArrayList groups = new ArrayList();
	protected ArrayList ipMasks = new ArrayList();
	
	//limits
	protected int maxUploadRate;
	protected int maxDownloadRate;
	protected int maxSimUploads;
	protected int maxSimDownloads;

	// time limits
	protected int idleTime = 0; // no limit
	protected int loginTime = 0;
	protected int lastAccessTime = 0;
	protected int timelimit;

	//quota
	protected float ratio = 3.0F;
	protected long credits;

	protected boolean deleted;
	protected boolean anonymous;

	/**
	 * Time last nuked specified in seconds since 1970
	 */
	protected long lastNuked;

	//login limits
	protected int maxLogins;
	protected int maxLoginsPerIP;

	//misc counters
	protected int timeToday;

	//action counters
	protected int logins;
	protected int timesNuked;
	protected long nukedBytes;

	//transfer counters
	
	protected long uploadedBytes;
	protected int uploadedFiles;
	protected int uploadedSeconds;
	
	protected long downloadedBytes;
	protected int downloadedFiles;
	protected int downloadedSeconds;
	
	protected long uploadedBytesWeek;
	protected int uploadedFilesWeek;
	protected int uploadedSecondsWeek;
	
	protected long downloadedBytesWeek;
	protected int downloadedFilesWeek;
	protected int downloadedSecondsWeek;
	
	protected long uploadedBytesMonth;
	protected int uploadedFilesMonth;
	protected int uploadedSecondsMonth;
	
	protected long downloadedBytesMonth;
	protected int downloadedFilesMonth;
	protected int downloadedSecondsMonth;
	
	protected long downloadedBytesDay;
	protected int downloadedFilesDay;
	protected int downloadedSecondsDay;

	protected long uploadedBytesDay;
	protected int uploadedFilesDay;
	protected int uploadedSecondsDay;
	
	public AbstractUser(String username) {
		this.username = username;
	}
	public boolean checkIP(String masks[]) {

		Perl5Matcher m = new Perl5Matcher();

		for(Iterator e2 = ipMasks.iterator(); e2.hasNext(); ) {
			String mask = (String) e2.next();

			Pattern p;
			try {
				p = new GlobCompiler().compile(mask);
			} catch (MalformedPatternException ex) {
				ex.printStackTrace();
				return false;
			}

			for (int i = 0; i < masks.length; i++) {
				String subject = masks[i];

				if (m.matches(subject, p)) {
					return true;
				}
				System.out.println("AbstractUser.checkIP(): \""+mask+"\" doesn't match \""+subject+"\"");
			}
		}
		System.out.println(getClass().getName()+".checkIP(): no match");
		return false;
	}

	//////////////////////////////// generic getters & setters ///////////////////////

	public void addIPMask(String mask) throws DuplicateElementException {
		if(ipMasks.contains(mask)) throw new DuplicateElementException("IP mask already added");
		ipMasks.add(mask);
	}
	/* (non-Javadoc)
	 * @see net.sf.drftpd.master.usermanager.User#removeIpMask(java.lang.String)
	 */
	public void removeIpMask(String mask) throws NoSuchFieldException {
		if(!ipMasks.remove(mask)) throw new NoSuchFieldException("User has no such ip mask");
	}

	/* (non-Javadoc)
	 * @see net.sf.drftpd.master.usermanager.User#removeGroup()
	 */
	public void removeGroup(String group) throws NoSuchFieldException {
		if(!groups.remove(group)) throw new NoSuchFieldException("User is not a member of that group");
	}

	public void addGroup(String group) throws DuplicateElementException {
		if(groups.contains(group)) throw new DuplicateElementException("User is already a member of that group");
		if(groups.contains(group)) return;
		groups.add(group);
	}

	public String getGroup() {
		if(groups.size() == 0) return "nogroup";
		return (String)groups.get(0);
	}

	public void updateCredits(long credits) {
		this.credits += credits;
	}
	
	public void updateUploadedBytes(long bytes) {
		this.uploadedBytes += bytes;
		this.uploadedBytesDay += bytes;
		this.uploadedBytesWeek += bytes;
		this.uploadedBytesMonth += bytes;
	}
	
	public void updateDownloadedBytes(long bytes) {
		this.downloadedBytes += bytes;
		this.downloadedBytesDay += bytes;
		this.downloadedBytesWeek += bytes;
		this.downloadedBytesMonth += bytes;
	}
	
	////////////////////////////////// autogenerated getters & setters below /////////////////////////////
	/**
	 * Get the user name.
	 */
	public String getUsername() {
		return username;
	}

	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getMaxSimDownloads() {
		return maxSimDownloads;
	}
	public void setMaxSimDownloads(int maxSimDownloads) {
		this.maxSimDownloads = maxSimDownloads;
	}

	/**
	 * Returns the maxSimUploads.
	 * @return int
	 */
	public int getMaxSimUploads() {
		return maxSimUploads;
	}

	/**
	 * Sets the maxSimUploads.
	 * @param maxSimUploads The maxSimUploads to set
	 */
	public void setMaxSimUploads(int maxSimUploads) {
		this.maxSimUploads = maxSimUploads;
	}

	/**
	 * Get the maximum idle time in second.
	 */
	public int getMaxIdleTime() {
		return idleTime;
	}

	/**
	 * Set the maximum idle time in second.
	 */
	public void setMaxIdleTime(int idleTime) {
		this.idleTime = idleTime;
	}

	/**
	 * Get maximum user upload rate in bytes/sec.
	 */
	public int getMaxUploadRate() {
		return maxUploadRate;
	}

	/**
	 * Set user maximum upload rate limit.
	 * Less than or equal to zero means no limit.
	 */
	public void setMaxUploadRate(int rate) {
		maxUploadRate = rate;
	}

	/**
	 * Get maximum user download rate in bytes/sec
	 */
	public int getMaxDownloadRate() {
		return maxDownloadRate;
	}

	/**
	 * Set user maximum download rate limit.
	 * Less than or equal to zero means no limit.
	 */
	public void setMaxDownloadRate(int rate) {
		maxDownloadRate = rate;
	}

	/**
	 * Get user loglin time.
	 */
	public int getLoginTime() {
		return loginTime;
	}

	/**
	 * Get last access time
	 */
	public long getLastAccessTime() {
		return lastAccessTime;
	}

	/**
	 * User login.
	 */
	public void login() {
		logins += 1;
		loginTime = (int) System.currentTimeMillis() / 1000;
		lastAccessTime = loginTime;
//		loggedIn = true;
	}

	/**
	 * User logout
	 */
	public void logout() {
		loginTime = 0;
//		loggedIn = false;
	}

	/**
	 * Is an active user (is removable)?
	 * Compares the last access time with the specified time.
	 */
	public boolean isActive(long currTime) {
		boolean bActive = true;
		long maxIdleTime = getMaxIdleTime() * 1000; // milliseconds
		if (maxIdleTime != 0L) {
			long idleTime = currTime - lastAccessTime;
			bActive = maxIdleTime > idleTime;
		}
		return bActive;
	}

	/**
	 * Is still active. Compares the last access time with the
	 * current time.
	 */
	public boolean isActive() {
		return isActive(System.currentTimeMillis());
	}

	/**
	 * Hit user - update last access time
	 */
	public void hitUser() {
		lastAccessTime = (int) System.currentTimeMillis() * 1000;
	}

	/** 
	 * String representation
	 */
	public String toString() {
		return username;
	}

	/**
	 * Returns the maxLogins.
	 * @return int
	 */
	public int getMaxLogins() {
		return maxLogins;
	}

	/**
	 * Returns the maxLoginsPerIP.
	 * @return int
	 */
	public int getMaxLoginsPerIP() {
		return maxLoginsPerIP;
	}

	/**
	 * Sets the maxLogins.
	 * @param maxLogins The maxLogins to set
	 */
	public void setMaxLogins(int maxLogins) {
		this.maxLogins = maxLogins;
	}

	/**
	 * Sets the maxLoginsPerIP.
	 * @param maxLoginsPerIP The maxLoginsPerIP to set
	 */
	public void setMaxLoginsPerIP(int maxLoginsPerIP) {
		this.maxLoginsPerIP = maxLoginsPerIP;
	}

	/**
	 * Returns the tagline.
	 * @return String
	 */
	public String getTagline() {
		return tagline;
	}

	/**
	 * Sets the tagline.
	 * @param tagline The tagline to set
	 */
	public void setTagline(String tagline) {
		this.tagline = tagline;
	}

	/**
	 * Returns the credits.
	 * @return long
	 */
	public long getCredits() {
		return credits;
	}

	/**
	 * Returns the idleTime.
	 * @return long
	 */
	public long getIdleTime() {
		return idleTime;
	}

	/**
	 * Returns the logins.
	 * @return int
	 */
	public int getLogins() {
		return logins;
	}

	/**
	 * Returns the ratio.
	 * @return float
	 */
	public float getRatio() {
		return ratio;
	}

	/**
	 * Sets the credits.
	 * @param credits The credits to set
	 */
	public void setCredits(long credits) {
		this.credits = credits;
	}

	/**
	 * Sets the idleTime.
	 * @param idleTime The idleTime to set
	 */
	public void setIdleTime(int idleTime) {
		this.idleTime = idleTime;
	}

	/**
	 * Sets the ratio.
	 * @param ratio The ratio to set
	 */
	public void setRatio(float ratio) {
		this.ratio = ratio;
	}

	/**
	 * Returns the downloadedBytes.
	 * @return long
	 */
	public long getDownloadedBytes() {
		return downloadedBytes;
	}

	/**
	 * Returns the downloadedBytesMonth.
	 * @return long
	 */
	public long getDownloadedBytesMonth() {
		return downloadedBytesMonth;
	}

	/**
	 * Returns the downloadedBytesWeek.
	 * @return long
	 */
	public long getDownloadedBytesWeek() {
		return downloadedBytesWeek;
	}

	/**
	 * Returns the uploadedBytes.
	 * @return long
	 */
	public long getUploadedBytes() {
		return uploadedBytes;
	}

	/**
	 * Returns the uploadedBytesMonth.
	 * @return long
	 */
	public long getUploadedBytesMonth() {
		return uploadedBytesMonth;
	}

	/**
	 * Returns the uploadedBytesWeek.
	 * @return long
	 */
	public long getUploadedBytesWeek() {
		return uploadedBytesWeek;
	}

	/**
	 * Sets the downloadedBytes.
	 * @param downloadedBytes The downloadedBytes to set
	 */
	public void setDownloadedBytes(long downloadedBytes) {
		this.downloadedBytes = downloadedBytes;
	}

	/**
	 * Sets the downloadedBytesMonth.
	 * @param downloadedBytesMonth The downloadedBytesMonth to set
	 */
	public void setDownloadedBytesMonth(long downloadedBytesMonth) {
		this.downloadedBytesMonth = downloadedBytesMonth;
	}

	/**
	 * Sets the downloadedBytesWeek.
	 * @param downloadedBytesWeek The downloadedBytesWeek to set
	 */
	public void setDownloadedBytesWeek(long downloadedBytesWeek) {
		this.downloadedBytesWeek = downloadedBytesWeek;
	}

	/**
	 * Sets the uploadedBytes.
	 * @param uploadedBytes The uploadedBytes to set
	 */
	public void setUploadedBytes(long uploadedBytes) {
		this.uploadedBytes = uploadedBytes;
	}

	/**
	 * Sets the uploadedBytesMonth.
	 * @param uploadedBytesMonth The uploadedBytesMonth to set
	 */
	public void setUploadedBytesMonth(long uploadedBytesMonth) {
		this.uploadedBytesMonth = uploadedBytesMonth;
	}

	/**
	 * Sets the uploadedBytesWeek.
	 * @param uploadedBytesWeek The uploadedBytesWeek to set
	 */
	public void setUploadedBytesWeek(long uploadedBytesWeek) {
		this.uploadedBytesWeek = uploadedBytesWeek;
	}

	/**
	 * Returns the downloadedBytesDay.
	 * @return long
	 */
	public long getDownloadedBytesDay() {
		return downloadedBytesDay;
	}

	/**
	 * Returns the uploadedBytesDay.
	 * @return long
	 */
	public long getUploadedBytesDay() {
		return uploadedBytesDay;
	}

	/**
	 * Sets the downloadedBytesDay.
	 * @param downloadedBytesDay The downloadedBytesDay to set
	 */
	public void setDownloadedBytesDay(long downloadedBytesDay) {
		this.downloadedBytesDay = downloadedBytesDay;
	}

	/**
	 * Sets the uploadedBytesDay.
	 * @param uploadedBytesDay The uploadedBytesDay to set
	 */
	public void setUploadedBytesDay(long uploadedBytesDay) {
		this.uploadedBytesDay = uploadedBytesDay;
	}

	/**
	 * Returns the deleted.
	 * @return boolean
	 */
	public boolean isDeleted() {
		return deleted;
	}

	/**
	 * Sets the deleted.
	 * @param deleted The deleted to set
	 */
	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * Returns the lastNuked.
	 * @return long
	 */
	public long getLastNuked() {
		return lastNuked;
	}

	/**
	 * Returns the nuked.
	 * @return int
	 */
	public int getTimesNuked() {
		return timesNuked;
	}

	/**
	 * Returns the nukedBytes.
	 * @return long
	 */
	public long getNukedBytes() {
		return nukedBytes;
	}

	/**
	 * Sets the nuked.
	 * @param nuked The nuked to set
	 */
	public void setTimesNuked(int nuked) {
		this.timesNuked = nuked;
	}

	/**
	 * Sets the nukedBytes.
	 * @param nukedBytes The nukedBytes to set
	 */
	public void setNukedBytes(long nukedBytes) {
		this.nukedBytes = nukedBytes;
	}

	/**
	 * Returns the anonymous.
	 * @return boolean
	 */
	public boolean isAnonymous() {
		return anonymous;
	}

	/**
	 * Sets the anonymous.
	 * @param anonymous The anonymous to set
	 */
	public void setAnonymous(boolean anonymous) {
		this.anonymous = anonymous;
	}

	/**
	 * Sets the lastAccessTime.
	 * @param lastAccessTime The lastAccessTime to set
	 */
	public void setLastAccessTime(int lastAccessTime) {
		this.lastAccessTime = lastAccessTime;
	}

	/**
	 * Returns the timeToday.
	 * @return long
	 */
	public long getTimeToday() {
		return timeToday;
	}

	/**
	 * Sets the timeToday.
	 * @param timeToday The timeToday to set
	 */
	public void setTimeToday(int timeToday) {
		this.timeToday = timeToday;
	}

	/**
	 * Returns the timelimit.
	 * @return int
	 */
	public int getTimelimit() {
		return timelimit;
	}

	/**
	 * Sets the timelimit.
	 * @param timelimit The timelimit to set
	 */
	public void setTimelimit(int timelimit) {
		this.timelimit = timelimit;
	}

	/**
	 * Returns the groups.
	 * @return Vector
	 */
	public Collection getGroups() {
		return groups;
	}

	/**
	 * Returns the ipMasks.
	 * @return Vector
	 */
	public Collection getIpMasks() {
		return ipMasks;
	}

	/**
	 * Returns the downloadedFiles.
	 * @return int
	 */
	public int getDownloadedFiles() {
		return downloadedFiles;
	}

	/**
	 * Returns the downloadedFilesDay.
	 * @return int
	 */
	public int getDownloadedFilesDay() {
		return downloadedFilesDay;
	}

	/**
	 * Returns the downloadedFilesMonth.
	 * @return int
	 */
	public int getDownloadedFilesMonth() {
		return downloadedFilesMonth;
	}

	/**
	 * Returns the downloadedFilesWeek.
	 * @return int
	 */
	public int getDownloadedFilesWeek() {
		return downloadedFilesWeek;
	}

	/**
	 * Returns the downloadedSeconds.
	 * @return int
	 */
	public int getDownloadedSeconds() {
		return downloadedSeconds;
	}

	/**
	 * Returns the downloadedSecondsDay.
	 * @return int
	 */
	public int getDownloadedSecondsDay() {
		return downloadedSecondsDay;
	}

	/**
	 * Returns the downloadedSecondsMonth.
	 * @return int
	 */
	public int getDownloadedSecondsMonth() {
		return downloadedSecondsMonth;
	}

	/**
	 * Returns the downloadedSecondsWeek.
	 * @return int
	 */
	public int getDownloadedSecondsWeek() {
		return downloadedSecondsWeek;
	}

	/**
	 * Returns the uploadedFiles.
	 * @return int
	 */
	public int getUploadedFiles() {
		return uploadedFiles;
	}

	/**
	 * Returns the uploadedFilesDay.
	 * @return int
	 */
	public int getUploadedFilesDay() {
		return uploadedFilesDay;
	}

	/**
	 * Returns the uploadedFilesMonth.
	 * @return int
	 */
	public int getUploadedFilesMonth() {
		return uploadedFilesMonth;
	}

	/**
	 * Returns the uploadedFilesWeek.
	 * @return int
	 */
	public int getUploadedFilesWeek() {
		return uploadedFilesWeek;
	}

	/**
	 * Returns the uploadedSeconds.
	 * @return int
	 */
	public int getUploadedSeconds() {
		return uploadedSeconds;
	}

	/**
	 * Returns the uploadedSecondsDay.
	 * @return int
	 */
	public int getUploadedSecondsDay() {
		return uploadedSecondsDay;
	}

	/**
	 * Returns the uploadedSecondsMonth.
	 * @return int
	 */
	public int getUploadedSecondsMonth() {
		return uploadedSecondsMonth;
	}

	/**
	 * Returns the uploadedSecondsWeek.
	 * @return int
	 */
	public int getUploadedSecondsWeek() {
		return uploadedSecondsWeek;
	}

	/**
	 * Sets the downloadedFiles.
	 * @param downloadedFiles The downloadedFiles to set
	 */
	public void setDownloadedFiles(int downloadedFiles) {
		this.downloadedFiles = downloadedFiles;
	}

	/**
	 * Sets the downloadedFilesDay.
	 * @param downloadedFilesDay The downloadedFilesDay to set
	 */
	public void setDownloadedFilesDay(int downloadedFilesDay) {
		this.downloadedFilesDay = downloadedFilesDay;
	}

	/**
	 * Sets the downloadedFilesMonth.
	 * @param downloadedFilesMonth The downloadedFilesMonth to set
	 */
	public void setDownloadedFilesMonth(int downloadedFilesMonth) {
		this.downloadedFilesMonth = downloadedFilesMonth;
	}

	/**
	 * Sets the downloadedFilesWeek.
	 * @param downloadedFilesWeek The downloadedFilesWeek to set
	 */
	public void setDownloadedFilesWeek(int downloadedFilesWeek) {
		this.downloadedFilesWeek = downloadedFilesWeek;
	}

	/**
	 * Sets the downloadedSeconds.
	 * @param downloadedSeconds The downloadedSeconds to set
	 */
	public void setDownloadedSeconds(int downloadedSeconds) {
		this.downloadedSeconds = downloadedSeconds;
	}

	/**
	 * Sets the downloadedSecondsDay.
	 * @param downloadedSecondsDay The downloadedSecondsDay to set
	 */
	public void setDownloadedSecondsDay(int downloadedSecondsDay) {
		this.downloadedSecondsDay = downloadedSecondsDay;
	}

	/**
	 * Sets the downloadedSecondsMonth.
	 * @param downloadedSecondsMonth The downloadedSecondsMonth to set
	 */
	public void setDownloadedSecondsMonth(int downloadedSecondsMonth) {
		this.downloadedSecondsMonth = downloadedSecondsMonth;
	}

	/**
	 * Sets the downloadedSecondsWeek.
	 * @param downloadedSecondsWeek The downloadedSecondsWeek to set
	 */
	public void setDownloadedSecondsWeek(int downloadedSecondsWeek) {
		this.downloadedSecondsWeek = downloadedSecondsWeek;
	}

	/**
	 * Sets the uploadedFiles.
	 * @param uploadedFiles The uploadedFiles to set
	 */
	public void setUploadedFiles(int uploadedFiles) {
		this.uploadedFiles = uploadedFiles;
	}

	/**
	 * Sets the uploadedFilesDay.
	 * @param uploadedFilesDay The uploadedFilesDay to set
	 */
	public void setUploadedFilesDay(int uploadedFilesDay) {
		this.uploadedFilesDay = uploadedFilesDay;
	}

	/**
	 * Sets the uploadedFilesMonth.
	 * @param uploadedFilesMonth The uploadedFilesMonth to set
	 */
	public void setUploadedFilesMonth(int uploadedFilesMonth) {
		this.uploadedFilesMonth = uploadedFilesMonth;
	}

	/**
	 * Sets the uploadedFilesWeek.
	 * @param uploadedFilesWeek The uploadedFilesWeek to set
	 */
	public void setUploadedFilesWeek(int uploadedFilesWeek) {
		this.uploadedFilesWeek = uploadedFilesWeek;
		update();
	}

	/**
	 * Sets the uploadedSeconds.
	 * @param uploadedSeconds The uploadedSeconds to set
	 */
	public void setUploadedSeconds(int uploadedSeconds) {
		this.uploadedSeconds = uploadedSeconds;
		update();
	}

	/**
	 * Sets the uploadedSecondsDay.
	 * @param uploadedSecondsDay The uploadedSecondsDay to set
	 */
	public void setUploadedSecondsDay(int uploadedSecondsDay) {
		this.uploadedSecondsDay = uploadedSecondsDay;
		update();
	}

	/**
	 * Sets the uploadedSecondsMonth.
	 * @param uploadedSecondsMonth The uploadedSecondsMonth to set
	 */
	public void setUploadedSecondsMonth(int uploadedSecondsMonth) {
		this.uploadedSecondsMonth = uploadedSecondsMonth;
		update();
	}

	/**
	 * Sets the uploadedSecondsWeek.
	 * @param uploadedSecondsWeek The uploadedSecondsWeek to set
	 */
	public void setUploadedSecondsWeek(int uploadedSecondsWeek) {
		this.uploadedSecondsWeek = uploadedSecondsWeek;
		update();
	}

	/**
	 * Sets the logins.
	 * @param logins The logins to set
	 */
	public void setLogins(int logins) {
		this.logins = logins;
		update();
	}

	/* (non-Javadoc)
	 * @see net.sf.drftpd.master.usermanager.User#setLastNuked(long)
	 */
	public void setLastNuked(long lastNuked) {
		this.lastNuked = lastNuked;
		update();
	}
	/* (non-Javadoc)
	 * @see net.sf.drftpd.master.usermanager.User#updateTimesNuked(int)
	 */
	public abstract void update();
	public void updateTimesNuked(int timesNuked) {
		this.timesNuked += timesNuked;
		update();
	}
	/* (non-Javadoc)
	 * @see net.sf.drftpd.master.usermanager.User#updateNukedBytes(long)
	 */
	public void updateNukedBytes(long bytes) {
		this.nukedBytes += bytes;
		update();
	}

}
