/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_mog_io_UnixFileSystem */

#ifndef _Included_se_mog_io_UnixFileSystem
#define _Included_se_mog_io_UnixFileSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_mog_io_UnixFileSystem
 * Method:    getDiskFreeSpace
 * Signature: (Lse/mog/io/File;)Lse/mog/io/DiskFreeSpace;
 */
JNIEXPORT jobject JNICALL Java_se_mog_io_UnixFileSystem_getDiskFreeSpace
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
